services:
  db:
    image: postgres:14
    container_name: health-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: health_app_development
    ports:
      - "5433:5432" 
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build:
      context: .
      args:
        RUBY_VERSION: 3.4.6
    container_name: health-web
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: dev_user
      PGPASSWORD: dev_pass
      RAILS_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/csce431/501_health:cached
    working_dir: /csce431/501_health
    depends_on:
      - db
    command: bash -lc "bundle install && bin/rails s -b 0.0.0.0 -p 3000"

volumes:
  db-data:
